// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC610SrVdAuCMv7Ae8PBPaQ4ZIlhJ8PFWI',
    appId: '1:767470877429:web:36d6bac8daa09dce0763bc',
    messagingSenderId: '767470877429',
    projectId: 'chatappfirebase-f51b9',
    authDomain: 'chatappfirebase-f51b9.firebaseapp.com',
    databaseURL: 'https://chatappfirebase-f51b9.firebaseio.com',
    storageBucket: 'chatappfirebase-f51b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C87H7WRR5KPlKuIMyxVEBwMeG7yxyKQ',
    appId: '1:767470877429:android:d89f9efd132c18ad0763bc',
    messagingSenderId: '767470877429',
    projectId: 'chatappfirebase-f51b9',
    databaseURL: 'https://chatappfirebase-f51b9.firebaseio.com',
    storageBucket: 'chatappfirebase-f51b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAod96Yl6-QFhg8yDddPtZsRGg2UcjjCUs',
    appId: '1:767470877429:ios:81b1f763174312920763bc',
    messagingSenderId: '767470877429',
    projectId: 'chatappfirebase-f51b9',
    databaseURL: 'https://chatappfirebase-f51b9.firebaseio.com',
    storageBucket: 'chatappfirebase-f51b9.appspot.com',
    androidClientId: '767470877429-mejjbk1s0b82lv8rtgic7h0u7tlqbn2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAod96Yl6-QFhg8yDddPtZsRGg2UcjjCUs',
    appId: '1:767470877429:ios:81b1f763174312920763bc',
    messagingSenderId: '767470877429',
    projectId: 'chatappfirebase-f51b9',
    databaseURL: 'https://chatappfirebase-f51b9.firebaseio.com',
    storageBucket: 'chatappfirebase-f51b9.appspot.com',
    androidClientId: '767470877429-mejjbk1s0b82lv8rtgic7h0u7tlqbn2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMeet',
  );
}
